### ISSUE TITLE
AttributeError: 'module' object has no attribute 'count_and_save_words'

### ISSUE THREAD

**Issue by xuloo** [realpython/flask-by-example#4]
checked out the repo, installed the requirements, ran the db update (after creating a new database).

I got the circular reference mentioned in the other issue here (changed 'Result' to '*') but when actually triggering a word count from the front-end i get the error in the title.

I haven't changed any of the code so i'm wondering what's causing this and how i might get around it.

**Comment by xuloo** [comment]
sorry, should make it more clear - i've got 3 terminal windows open

1. redis-server
2. python worker.py
3. python app.py

the error is appearing in window (2) - window (3) just repeatedly polls the server (as it should)

**Comment by mjhea0** [comment]
@xuloo - which version of python are you using? 2 or 3?

**Comment by xuloo** [comment]
sorry for the delay in responding - i'm using python 3

here's the stack if that helps...

AttributeError: 'module' object has no attribute 'download_and_convert'
Traceback (most recent call last):
  File "/Users/trevorburton-mccreadie/Envs/bennyhillmachine/lib/python3.4/site-packages/rq/worker.py", line 543, in perform_job
    job.func_name,
  File "/Users/trevorburton-mccreadie/Envs/bennyhillmachine/lib/python3.4/site-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/Users/trevorburton-mccreadie/Envs/bennyhillmachine/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/Users/trevorburton-mccreadie/Envs/bennyhillmachine/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)

**Comment by xuloo** [comment]
Actually, this stack was from another project - but it's the flask-by-example repo but with some tweaks to the background job (and a different name for the background job).

A fresh checkout of the flask-by-example repo and setting up virtual env with

mkvirtualenv --python=/usr/local/bin/python3 wordcount

gives

06:52:10 default: __main__.count_and_save_words('http://www.bbc.co.uk') (603cd040-9488-4d93-81b0-c8b0cb4f68d3)
06:52:10 AttributeError: 'module' object has no attribute 'count_and_save_words'
Traceback (most recent call last):
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'count_and_save_words'
Traceback (most recent call last):
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/Users/trevorburton-mccreadie/Envs/wordcount/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'count_and_save_words'
06:52:10 Moving job to failed queue.
06:52:10 
06:52:10 *** Listening on default...

**Comment by mjhea0** [comment]
Can I see your code, please.

**Comment by xuloo** [comment]
The second stack trace happens when i clone the repository of this project and run it (after setting up the database, of course) - my own code just causes the same 'module not found' error

**Comment by xuloo** [comment]
the 'wordcount' directory in the stack trace is THIS repository

**Comment by mjhea0** [comment]
It's really hard to debug this since I'm not getting the same error. Can you clone and then follow these steps:

https://github.com/realpython/flask-by-example#quick-start

**Comment by xuloo** [comment]
thanks for your help!

I've followed the steps (btw, the --python flag is missing from the mkvirtualenv call on that page - i added it to ensure i'm using python3 as per the instructions here https://realpython.com/blog/python/flask-by-example-part-1-project-setup/ - i also tried it with python 2.7 (the default if i omit the --python flag) and that gives the same result.)

I can't attach all the code as it's too big for github issue attachments but it's a clean clone of this repo. I've changed absolutely nothing. Here's the stack trace again.

08:56:21 default: __main__.count_and_save_words('http://www.bbc.co.uk') (6ab1a965-ae85-4075-9f9d-7d553b19d5cf)
08:56:21 AttributeError: 'module' object has no attribute 'count_and_save_words'
Traceback (most recent call last):
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'count_and_save_words'
Traceback (most recent call last):
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/Users/trevorburton-mccreadie/Envs/wordcounts/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'count_and_save_words'
08:56:21 Moving job to failed queue.
08:56:21 
08:56:21 *** Listening on default...

This is really confusing because i HAVE had this working before - but when i've gone back to try again to remind myself of how it works suddenly i'm seeing this problem.

**Comment by mjhea0** [comment]
Okay. So the issue is with Python 2.7, correct?

**Comment by xuloo** [comment]
No, it's with 2.7 and 3.4 - whichever i use i see the same problem - module object has no attribute count_and_save_words

**Comment by mjhea0** [comment]
https://realpython.com/blog/python/flask-by-example-implementing-a-redis-task-queue/#comment-1755179526
