### ISSUE TITLE
Circular dependency in app.py

### ISSUE THREAD

**Issue by sindhus** [realpython/flask-by-example#5]
When I try to run app.py, I get:

```
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    from models import Result
  File "/Users/sindhus/Documents/the-real-flask-by-example/models.py", line 1, in <module>
    from app import db
  File "/Users/sindhus/Documents/the-real-flask-by-example/app.py", line 27, in <module>
    from models import Result
ImportError: cannot import name 'Result'
```

**Comment by mjhea0** [comment]
Updated in new release
